// Generated by gencpp from file reflector_localization/Feature2DWithID.msg
// DO NOT EDIT!


#ifndef REFLECTOR_LOCALIZATION_MESSAGE_FEATURE2DWITHID_H
#define REFLECTOR_LOCALIZATION_MESSAGE_FEATURE2DWITHID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reflector_localization
{
template <class ContainerAllocator>
struct Feature2DWithID_
{
  typedef Feature2DWithID_<ContainerAllocator> Type;

  Feature2DWithID_()
    : x(0.0)
    , y(0.0)
    , ID(0)  {
    }
  Feature2DWithID_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , ID(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef int32_t _ID_type;
  _ID_type ID;





  typedef boost::shared_ptr< ::reflector_localization::Feature2DWithID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reflector_localization::Feature2DWithID_<ContainerAllocator> const> ConstPtr;

}; // struct Feature2DWithID_

typedef ::reflector_localization::Feature2DWithID_<std::allocator<void> > Feature2DWithID;

typedef boost::shared_ptr< ::reflector_localization::Feature2DWithID > Feature2DWithIDPtr;
typedef boost::shared_ptr< ::reflector_localization::Feature2DWithID const> Feature2DWithIDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reflector_localization::Feature2DWithID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reflector_localization::Feature2DWithID_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::reflector_localization::Feature2DWithID_<ContainerAllocator1> & lhs, const ::reflector_localization::Feature2DWithID_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.ID == rhs.ID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::reflector_localization::Feature2DWithID_<ContainerAllocator1> & lhs, const ::reflector_localization::Feature2DWithID_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace reflector_localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::reflector_localization::Feature2DWithID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflector_localization::Feature2DWithID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflector_localization::Feature2DWithID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflector_localization::Feature2DWithID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflector_localization::Feature2DWithID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflector_localization::Feature2DWithID_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reflector_localization::Feature2DWithID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c337f99b9f380063a41aa7266459d417";
  }

  static const char* value(const ::reflector_localization::Feature2DWithID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc337f99b9f380063ULL;
  static const uint64_t static_value2 = 0xa41aa7266459d417ULL;
};

template<class ContainerAllocator>
struct DataType< ::reflector_localization::Feature2DWithID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reflector_localization/Feature2DWithID";
  }

  static const char* value(const ::reflector_localization::Feature2DWithID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reflector_localization::Feature2DWithID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"int32 ID\n"
;
  }

  static const char* value(const ::reflector_localization::Feature2DWithID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reflector_localization::Feature2DWithID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.ID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Feature2DWithID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reflector_localization::Feature2DWithID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reflector_localization::Feature2DWithID_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "ID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFLECTOR_LOCALIZATION_MESSAGE_FEATURE2DWITHID_H
