// Generated by gencpp from file reflector_localization/IntensityPoint2D.msg
// DO NOT EDIT!


#ifndef REFLECTOR_LOCALIZATION_MESSAGE_INTENSITYPOINT2D_H
#define REFLECTOR_LOCALIZATION_MESSAGE_INTENSITYPOINT2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reflector_localization
{
template <class ContainerAllocator>
struct IntensityPoint2D_
{
  typedef IntensityPoint2D_<ContainerAllocator> Type;

  IntensityPoint2D_()
    : x(0.0)
    , y(0.0)
    , intensity(0.0)  {
    }
  IntensityPoint2D_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , intensity(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _intensity_type;
  _intensity_type intensity;





  typedef boost::shared_ptr< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> const> ConstPtr;

}; // struct IntensityPoint2D_

typedef ::reflector_localization::IntensityPoint2D_<std::allocator<void> > IntensityPoint2D;

typedef boost::shared_ptr< ::reflector_localization::IntensityPoint2D > IntensityPoint2DPtr;
typedef boost::shared_ptr< ::reflector_localization::IntensityPoint2D const> IntensityPoint2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reflector_localization::IntensityPoint2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::reflector_localization::IntensityPoint2D_<ContainerAllocator1> & lhs, const ::reflector_localization::IntensityPoint2D_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.intensity == rhs.intensity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::reflector_localization::IntensityPoint2D_<ContainerAllocator1> & lhs, const ::reflector_localization::IntensityPoint2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace reflector_localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fd3773deaf67e73a5119f531a0f53f4";
  }

  static const char* value(const ::reflector_localization::IntensityPoint2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fd3773deaf67e73ULL;
  static const uint64_t static_value2 = 0xa5119f531a0f53f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reflector_localization/IntensityPoint2D";
  }

  static const char* value(const ::reflector_localization::IntensityPoint2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#IntensityPoint2D 单个点的强度\n"
"float64 x\n"
"float64 y\n"
"float64 intensity\n"
;
  }

  static const char* value(const ::reflector_localization::IntensityPoint2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.intensity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IntensityPoint2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reflector_localization::IntensityPoint2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reflector_localization::IntensityPoint2D_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "intensity: ";
    Printer<double>::stream(s, indent + "  ", v.intensity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFLECTOR_LOCALIZATION_MESSAGE_INTENSITYPOINT2D_H
